### ISSUE TITLE
class.sanalpos.php 95.satır hata

### ISSUE THREAD

**Issue by kobeumut** [ufukOzarslan/SanalPosEntegrasyon#1]
```
    $hashparams = $_POST["HASHPARAMS"];
    $hashparamsval = $_POST["HASHPARAMSVAL"];
```

class.sanalpos.php de 95. satırda HASHPARAMS ve altındaki gibi bir değer belirtilmediği için hata veriyor tam olarak burada isteneni çözemedim kuveyttürke entegre etmeye çalışıyorum.

**Comment by ufukOzarslan** [comment]
```
 $hashparams = $_POST["HASHPARAMS"];
 $hashparamsval = $_POST["HASHPARAMSVAL"];
```

Bankadan size dönen değer, burada bir hata yok, buraya kadar gelmiyorsa, banka tarafından size hangi istek gönderiliyor? Kontrol etmeniz gerekiyor.
