### ISSUE TITLE
Paypal,Paycell ve İnnial kart eklemek istediğimiz de onların kütüphanesini mi? kullanmak lazım?

### ISSUE THREAD

**Issue by omerfeyyaz** [ufukOzarslan/SanalPosEntegrasyon#2]
başlıkta yazıldığı gibi bu bankalara ek olarak paypal,paycell,innial ve enpara gibi kartlarıda kullanmak için onların kütüphanelerini mi? kullanmalıyız?

**Comment by ufukOzarslan** [comment]
evet, onlarında kendi php sınıfları veya servisleri mevcuttur.
