### ISSUE TITLE
Güvenlik Uyarisi. Sayisal Imza Geçerli Degil

### ISSUE THREAD

**Issue by nrtszr** [ufukOzarslan/SanalPosEntegrasyon#3]
Test ettiğimde "Güvenlik Uyarisi. Sayisal Imza Geçerli Degil" hatası alıyorum.
Sizce ne yapabilirim?

**Comment by ufukOzarslan** [comment]
@nrtszr bankanızla iletişime geçebilirseniz size yardımcı olacaktır
